# Generated by Django 2.2.13 on 2020-07-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueId', models.CharField(max_length=100, unique=True)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.CharField(max_length=100)),
                ('Upvotes', models.IntegerField()),
                ('Downvotes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CurrentPoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Polls')),
            ],
        ),
        migrations.CreateModel(
            name='UpvoteLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=200)),
                ('QuestionUpvote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserModel'),
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Polls'),
        ),
        migrations.CreateModel(
            name='DownvoteLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=200)),
                ('QuestionDownvote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
