# Generated by Django 2.2.13 on 2020-07-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downvotelogs',
            old_name='QuestionDownvote',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='upvotelogs',
            old_name='QuestionUpvote',
            new_name='Question',
        ),
    ]
