# Generated by Django 2.2.13 on 2020-07-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200720_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
    ]
