# Generated by Django 2.2.13 on 2020-07-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvotelogs',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='upvotelogs',
            name='IP',
        ),
        migrations.AddField(
            model_name='downvotelogs',
            name='UserFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.UserModel'),
        ),
        migrations.AddField(
            model_name='upvotelogs',
            name='UserFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.UserModel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
