# Generated by Django 2.2.13 on 2020-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='UniqueId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
