# Generated by Django 2.2.13 on 2020-07-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200720_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Downvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Upvotes',
        ),
    ]
